# Add 'documentation' label if any .md files change
documentation:
  - '**/*.md'

# Add 'tests' label if test files change
tests:
  - 'tests/**/*'
  - '**/*test.py'

# Add 'dependencies' label if requirements change
dependencies:
  - 'requirements.txt'
  - 'package.json'
  - 'package-lock.json'
