# Add 'documentation' label if any .md files change
documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'

# Add 'tests' label if test files change
tests:
  - changed-files:
    - any-glob-to-any-file:
      - '**/tests/**.py'
      - '**/tests/**/*test*.py'

# Add 'workflows' label if yml file changes
workflows:
  - changed-files:
    - any-glob-to-any-file:
      - '**/workflows/*.yml'
